using System.Reflection;

namespace Foundatio.Mediator.Utility;

internal static class Helpers
{
    public static void AddGeneratedFileHeader(this IndentedStringBuilder source)
    {
        source.AppendLine("// <auto-generated>");
        source.AppendLine("// This file was generated by Foundatio.Mediator source generators.");
        source.AppendLine("// Changes to this file may be lost when the code is regenerated.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine();
        source.AppendLine("#nullable enable");
        source.AppendLine();
    }

    public static void AddGeneratedCodeAttribute(this IndentedStringBuilder source)
    {
        var toolName = "Foundatio.Mediator";
        var toolVersion = GetToolVersion();

        source.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", \"{toolVersion}\")]");
    }

    private static string GetToolVersion()
    {
        var asm = typeof(Helpers).Assembly;

        var infoVersion = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        if (!String.IsNullOrEmpty(infoVersion))
            return infoVersion!;

        return asm.GetName().Version?.ToString() ?? "1.0.0";
    }

    public static string ToIdentifier(this string name)
    {
        if (String.IsNullOrEmpty(name))
            return String.Empty;

        return new string(name.Select(c => Char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());
    }

    public static string ToCamelCase(this string name)
    {
        if (String.IsNullOrEmpty(name))
            return String.Empty;

        return Char.ToLower(name[0]) + name.Substring(1);
    }
}
