using System.Reflection;

namespace Foundatio.Mediator.Utility;

internal static class Helpers
{
    public static void AddGeneratedFileHeader(this IndentedStringBuilder source)
    {
        var semanticVersion = GetSemanticVersion();

        source.AppendLine("// <auto-generated>");
        source.AppendLine($"// Generated by Foundatio.Mediator v{semanticVersion}");
        source.AppendLine("// Changes to this file may be lost when the code is regenerated.");
        source.AppendLine("// </auto-generated>");
        source.AppendLine();
        source.AppendLine("#nullable enable");
        source.AppendLine();
    }

    public static void AddGeneratedCodeAttribute(this IndentedStringBuilder source)
    {
        var toolName = "Foundatio.Mediator";
        var toolVersion = GetFullVersion();

        source.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{toolName}\", \"{toolVersion}\")]");
    }

    /// <summary>
    /// Gets the semantic version (e.g., "1.0.0-rc.3.9") without the commit hash suffix.
    /// </summary>
    private static string GetSemanticVersion()
    {
        var fullVersion = GetFullVersion();

        // Remove the +commitHash suffix if present
        var plusIndex = fullVersion.IndexOf('+');
        if (plusIndex > 0)
            return fullVersion.Substring(0, plusIndex);

        return fullVersion;
    }

    /// <summary>
    /// Gets the full informational version including commit hash (e.g., "1.0.0-rc.3.9+abc123").
    /// </summary>
    private static string GetFullVersion()
    {
        var asm = typeof(Helpers).Assembly;

        var infoVersion = asm.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        if (!String.IsNullOrEmpty(infoVersion))
            return infoVersion!;

        return asm.GetName().Version?.ToString() ?? "1.0.0";
    }

    public static string ToIdentifier(this string name)
    {
        if (String.IsNullOrEmpty(name))
            return String.Empty;

        var identifier = new string(name.Select(c => Char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());
        
        // C# identifiers cannot start with a digit, so prefix with underscore if needed
        if (identifier.Length > 0 && Char.IsDigit(identifier[0]))
            return "_" + identifier;

        return identifier;
    }

    public static string ToCamelCase(this string name)
    {
        if (String.IsNullOrEmpty(name))
            return String.Empty;

        return Char.ToLower(name[0]) + name.Substring(1);
    }
}
