using System.Collections.Immutable;
using System.Text.RegularExpressions;
using Foundatio.Xunit;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Foundatio.Mediator.Tests;

public abstract class GeneratorTestBase(ITestOutputHelper output) : TestWithLoggingBase(output)
{
    protected async Task VerifyGenerated(string source, params IIncrementalGenerator[] generators)
    {
        await VerifyGenerated(source, null, null, generators);
    }

    protected async Task VerifyGenerated(string source, AnalyzerConfigOptionsProvider? optionsProvider, params IIncrementalGenerator[] generators)
    {
        await VerifyGenerated(source, optionsProvider, null, generators);
    }

    protected async Task VerifyGenerated(string source, AnalyzerConfigOptionsProvider? optionsProvider, MetadataReference[]? additionalReferences, params IIncrementalGenerator[] generators)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Preview)
            .WithFeatures([new KeyValuePair<string, string>("InterceptorsNamespaces", "Foundatio.Mediator")]);
        var compilation = CreateCompilation(source, parseOptions, additionalReferences);

        var sourceGenerators = generators.Select(g => g.AsSourceGenerator());
        GeneratorDriver driver = CSharpGeneratorDriver.Create(sourceGenerators, additionalTexts: null,
            parseOptions: parseOptions, optionsProvider: optionsProvider);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        AssertNoCompilationDiagnostics(outputCompilation);

        var genResult = driver.GetRunResult();

        await Verify(new
        {
            Diagnostics = diagnostics,
            GeneratorDiagnostics = genResult.Diagnostics,
            GeneratedTrees = genResult.Results
                    .SelectMany(r => r.GeneratedSources)
                    .Select(s => new { s.HintName, Source = s.SourceText.ToString() })
                    .OrderBy(s => s.HintName)
                    .ToList()
        })
            .ScrubLines(l => l.Contains("// <auto-generated>"))
            .AddScrubber(sb =>
            {
                var text = sb.ToString();

                // Scrub GeneratedCode attribute version
                text = Regex.Replace(text,
                    @"GeneratedCode\(""Foundatio\.Mediator"",\s*""[^""]+""\)",
                    "GeneratedCode(\"Foundatio.Mediator\", \"<version>\")");

                // Scrub header comment version
                text = Regex.Replace(text,
                    @"// Generated by Foundatio\.Mediator v[^\r\n]+",
                    "// Generated by Foundatio.Mediator v<version>");

                // Scrub InterceptsLocation encoded data (contains file paths that differ across OS)
                text = Regex.Replace(text,
                    @"InterceptsLocation\(1,\s*""[^""]+?""\)",
                    "InterceptsLocation(1, \"<data>\")");

                sb.Clear().Append(text);
            });
    }

    protected (Compilation Compilation,
        ImmutableArray<Diagnostic> Diagnostics,
        IReadOnlyList<(string HintName, string Source)> GeneratedTrees)
        RunGenerator(string source, IIncrementalGenerator[] generators,
            AnalyzerConfigOptionsProvider? optionsProvider = null,
            MetadataReference[]? additionalReferences = null,
            bool assertCleanCompilation = true)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Preview)
            .WithFeatures([new KeyValuePair<string, string>("InterceptorsNamespaces", "Foundatio.Mediator")]);
        var compilation = CreateCompilation(source, parseOptions, additionalReferences);

        var sourceGenerators = generators.Select(g => g.AsSourceGenerator()).ToImmutableArray();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(sourceGenerators, additionalTexts: null,
            parseOptions: parseOptions, optionsProvider: optionsProvider);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        var genResult = driver.GetRunResult();
        var trees = genResult.Results
            .SelectMany(r => r.GeneratedSources)
            .Select(s => (s.HintName, s.SourceText.ToString()))
            .ToList();

        if (assertCleanCompilation)
            AssertNoCompilationDiagnostics(outputCompilation);

        return (outputCompilation, diagnostics, trees);
    }

    /// <summary>
    /// Asserts that compilation of the generated code has no errors or warnings.
    /// Only inspects diagnostics originating from generated source files (*.g.cs),
    /// not from the user-authored test input. Filters out diagnostics that are inherent
    /// to in-memory test compilations (missing assembly references, interceptors feature
    /// flag, etc.) since these are test infrastructure limitations, not generator bugs.
    /// </summary>
    protected static void AssertNoCompilationDiagnostics(Compilation compilation)
    {
        var problems = compilation.GetDiagnostics()
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .Where(d => d.Location.SourceTree?.FilePath.EndsWith(".g.cs") == true) // Only check generated code
            .ToList();

        if (problems.Count > 0)
        {
            var messages = string.Join(Environment.NewLine, problems.Select(d => $"  {d.Severity} {d.Id}: {d.GetMessage()} @ {d.Location}"));
            Assert.Fail($"Generated code produced {problems.Count} compilation diagnostic(s):{Environment.NewLine}{messages}");
        }
    }

    /// <summary>
    /// Compiles source code into an in-memory assembly that can be used as
    /// an additional reference for cross-assembly generator tests.
    /// Note: Does not run the source generator, so handler wrapper types are not
    /// emitted. Cross-assembly interceptor tests that reference these wrappers
    /// should use assertCleanCompilation: false since CS0234 is expected.
    /// </summary>
    internal static MetadataReference CreateAssembly(string source, string assemblyName = "TestAssembly")
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.CSharp11);
        var syntaxTree = CSharpSyntaxTree.ParseText(source, parseOptions);

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IMediator).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Diagnostics.Stopwatch).Assembly.Location),
        };

        var coreLibDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        var runtimePath = Path.Combine(coreLibDir, "System.Runtime.dll");
        var netstandardPath = Path.Combine(coreLibDir, "netstandard.dll");

        if (File.Exists(runtimePath))
            references.Add(MetadataReference.CreateFromFile(runtimePath));
        if (File.Exists(netstandardPath))
            references.Add(MetadataReference.CreateFromFile(netstandardPath));

        var compilation = CSharpCompilation.Create(
            assemblyName: assemblyName,
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        using var ms = new MemoryStream();
        var emitResult = compilation.Emit(ms);

        if (!emitResult.Success)
        {
            var errors = string.Join(Environment.NewLine, emitResult.Diagnostics
                .Where(d => d.Severity == DiagnosticSeverity.Error)
                .Select(d => d.ToString()));
            throw new InvalidOperationException($"Failed to compile assembly '{assemblyName}':{Environment.NewLine}{errors}");
        }

        ms.Seek(0, SeekOrigin.Begin);
        return MetadataReference.CreateFromStream(ms);
    }

    protected static Compilation CreateCompilation(string source, CSharpParseOptions parseOptions, MetadataReference[]? additionalReferences = null, string assemblyName = "Tests")
    {
        var runtimeDir = System.IO.Path.GetDirectoryName(typeof(object).Assembly.Location)!;

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.ServiceCollection)
                .Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IMediator).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(MediatorGenerator).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Diagnostics.Activity).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Exception).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(ValueTask).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(IServiceProvider).Assembly.Location),
        };

        // Add additional runtime assemblies for proper type resolution
        var additionalAssemblies = new[]
        {
            "netstandard.dll",
            "System.Runtime.dll",
            "System.Collections.dll",
            "System.Threading.dll",
            "System.Threading.Tasks.dll",
            "System.ComponentModel.dll",
            "System.Threading.Tasks.Extensions.dll",
            "System.Console.dll",
            "System.Security.Claims.dll",
            "System.Linq.dll",
            "System.Net.ServerSentEvents.dll",
            "System.Private.Uri.dll",
        };

        foreach (var asm in additionalAssemblies)
        {
            var path = System.IO.Path.Combine(runtimeDir, asm);
            if (System.IO.File.Exists(path))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        if (additionalReferences != null)
        {
            references.AddRange(additionalReferences);
        }

        return CSharpCompilation.Create(
            assemblyName: assemblyName,
            syntaxTrees: [CSharpSyntaxTree.ParseText(source, parseOptions)],
            references: references,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    public static AnalyzerConfigOptionsProvider CreateOptions(params (string Key, string Value)[] globalOptions)
    {
        var dict = globalOptions.ToImmutableDictionary(kv => kv.Key, kv => kv.Value);
        return new SimpleOptionsProvider(dict);
    }

    /// <summary>
    /// Returns ASP.NET Core metadata references so the endpoint generator activates.
    /// These are deliberately NOT included in <see cref="CreateCompilation"/> because
    /// their presence changes generator behavior (enables endpoint generation).
    /// Pass them via <c>additionalReferences</c> only in endpoint-specific tests.
    /// </summary>
    protected static MetadataReference[] GetAspNetCoreReferences()
    {
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        var aspNetCoreDir = Path.GetFullPath(
            Path.Combine(runtimeDir, "..", "..", "Microsoft.AspNetCore.App",
                new DirectoryInfo(runtimeDir).Name));

        if (!Directory.Exists(aspNetCoreDir))
        {
            Assert.Skip("ASP.NET Core shared framework not found; endpoint generation tests require the ASP.NET Core SDK");
            return [];
        }

        var assemblies = new[]
        {
            "Microsoft.AspNetCore.dll",
            "Microsoft.AspNetCore.Authentication.Abstractions.dll",
            "Microsoft.AspNetCore.Authorization.dll",
            "Microsoft.AspNetCore.Authorization.Policy.dll",
            "Microsoft.AspNetCore.Http.Abstractions.dll",
            "Microsoft.AspNetCore.Http.dll",
            "Microsoft.AspNetCore.Http.Extensions.dll",
            "Microsoft.AspNetCore.Http.Features.dll",
            "Microsoft.AspNetCore.Http.Results.dll",
            "Microsoft.AspNetCore.Metadata.dll",
            "Microsoft.AspNetCore.Routing.dll",
            "Microsoft.AspNetCore.Routing.Abstractions.dll",
            "Microsoft.AspNetCore.Mvc.Core.dll",
            "Microsoft.AspNetCore.OpenApi.dll",
            "Microsoft.Extensions.Primitives.dll",
            "Microsoft.Net.Http.Headers.dll",
        };

        var refs = new List<MetadataReference>();
        foreach (var assembly in assemblies)
        {
            var path = Path.Combine(aspNetCoreDir, assembly);
            if (File.Exists(path))
                refs.Add(MetadataReference.CreateFromFile(path));
        }

        if (refs.Count == 0)
        {
            Assert.Skip("No ASP.NET Core assemblies found in the shared framework directory");
            return [];
        }

        return refs.ToArray();
    }

    protected string? GenerateEndpointSource(string source)
    {
        var refs = GetAspNetCoreReferences();
        if (refs.Length == 0) return null;

        var (_, _, trees) = RunGenerator(source, [new MediatorGenerator()], additionalReferences: refs);
        return trees.FirstOrDefault(t => t.HintName == "_MediatorEndpoints.g.cs").Source;
    }

    /// <summary>
    /// Asserts the generated source contains an endpoint with the given HTTP method and full route.
    /// Parses the generated log lines which have the format:
    ///   writeLog("  GET  /api/todos/{todoId}  → Handler.Method(Message) (convention)");
    /// This validates the fully composed path including route prefix and category.
    /// </summary>
    protected static void AssertEndpoint(string endpointSource, string httpMethod, string fullRoute)
    {
        var endpoints = ParseEndpointLogEntries(endpointSource);

        Assert.True(endpoints.Any(e => e.Method == httpMethod && e.Route == fullRoute),
            $"Expected {httpMethod} {fullRoute} not found.\n" +
            $"Found endpoints:\n{string.Join("\n", endpoints.Select(e => $"  {e.Method} {e.Route}"))}\n\n" +
            $"Generated source:\n{endpointSource}");
    }

    /// <summary>
    /// Asserts the generated source does NOT contain the given route segment in any endpoint route.
    /// Parses the generated log lines for the fully composed routes.
    /// </summary>
    protected static void AssertNoRouteContains(string endpointSource, string routeSegment)
    {
        var endpoints = ParseEndpointLogEntries(endpointSource);

        foreach (var (method, route) in endpoints)
        {
            Assert.False(route.Contains(routeSegment),
                $"Route '{route}' unexpectedly contains '{routeSegment}'.\nEndpoint: {method} {route}");
        }
    }

    /// <summary>
    /// Parses the writeLog lines in generated endpoint source to extract (HttpMethod, FullRoute) pairs.
    /// Log line format: writeLog("  GET  /api/todos/{todoId}  → Handler.Method(Msg) (convention)");
    /// </summary>
    protected static List<(string Method, string Route)> ParseEndpointLogEntries(string endpointSource)
    {
        var results = new List<(string Method, string Route)>();
        foreach (var line in endpointSource.Split('\n'))
        {
            var trimmed = line.Trim();

            // Match: writeLog("  GET  /api/route  → Handler (convention|explicit)");
            if (!trimmed.StartsWith("writeLog(\"  "))
                continue;

            // Strip writeLog(" and trailing ");
            var inner = trimmed.Substring("writeLog(\"".Length);
            var closeIdx = inner.LastIndexOf("\");", StringComparison.Ordinal);
            if (closeIdx < 0)
                continue;
            inner = inner.Substring(0, closeIdx).Trim();

            // Format: "METHOD  /route  → handler (source)"
            var arrowIdx = inner.IndexOf("→", StringComparison.Ordinal);
            if (arrowIdx < 0)
                continue;

            var methodAndRoute = inner.Substring(0, arrowIdx).Trim();
            var firstSpace = methodAndRoute.IndexOf(' ');
            if (firstSpace < 0)
                continue;

            var method = methodAndRoute.Substring(0, firstSpace).Trim();
            var route = methodAndRoute.Substring(firstSpace).Trim();
            results.Add((method, route));
        }
        return results;
    }

    protected static string ToKebabCase(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;

        var result = new System.Text.StringBuilder();
        for (var i = 0; i < value.Length; i++)
        {
            var c = value[i];
            if (char.IsUpper(c) && i > 0)
            {
                result.Append('-');
            }
            result.Append(char.ToLowerInvariant(c));
        }
        return result.ToString();
    }

    private sealed class SimpleOptionsProvider : AnalyzerConfigOptionsProvider
    {
        private readonly ImmutableDictionary<string, string> _globals;

        public SimpleOptionsProvider(ImmutableDictionary<string, string> globals)
        {
            _globals = globals;
            GlobalOptions = new SimpleOptions(_globals);
        }

        public override AnalyzerConfigOptions GlobalOptions { get; }
        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => new SimpleOptions(_globals);
        public override AnalyzerConfigOptions GetOptions(AdditionalText textFile) => new SimpleOptions(_globals);

        private sealed class SimpleOptions : AnalyzerConfigOptions
        {
            private readonly ImmutableDictionary<string, string> _globals;

            public SimpleOptions(ImmutableDictionary<string, string> globals)
            {
                _globals = globals;
            }

            public override bool TryGetValue(string key, out string value)
            {
                if (_globals.TryGetValue(key, out var v))
                {
                    value = v;
                    return true;
                }
                value = string.Empty;
                return false;
            }
        }
    }
}
