using Common.Module;
using Foundatio.Mediator;
using Orders.Module;
using Products.Module;
using Reports.Module;

var builder = WebApplication.CreateBuilder(args);

var apiVersions = new[] { "2025-01-15", "2025-06-01" };

builder.Services.AddHttpContextAccessor();
builder.Services.AddOpenApiDocs(apiVersions);
builder.Services.AddDemoAuthentication();

// Add Foundatio.Mediator — all referenced module assemblies are auto-discovered
builder.Services.AddMediator();

// Add module services
builder.Services.AddCommonModule();
builder.Services.AddOrdersModule();
builder.Services.AddProductsModule();
builder.Services.AddReportsModule();

var app = builder.Build();

// Serve static files from the SPA
app.UseDefaultFiles();
app.MapStaticAssets();

app.MapOpenApiDocs("Modular Monolith API", apiVersions);

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapDemoAuthEndpoints();

// Map API endpoints generated by Foundatio.Mediator source generator based on request handlers in the modules.
app.MapMediatorEndpoints();

// SPA fallback - serves index.html for client-side routing
app.MapFallbackToFile("/index.html");

app.Run();

