name: Deploy Documentation

on: [push]
#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean npm cache and dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm cache clean --force
      working-directory: docs

    - name: Install dependencies
      run: npm install --force
      working-directory: docs

    - name: Extract version from tag
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build documentation
      run: npm run build
      working-directory: docs
      env:
        NODE_ENV: production
        VITE_VERSION: ${{ steps.version.outputs.version }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/.vitepress/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
